server:
  port: 8888

spring:
  application:
    name: gateway-service    # Changed from Gateway to gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: client-service-route
          uri: lb://service-client
          predicates:
            - Path=/api/client/**
        - id: car-service-route
          uri: lb://service-car
          predicates:
            - Path=/api/car/**, /api/performance/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always