server:
  port: 8082

spring:
  application:
    name: service-car
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
  datasource:
    driver-class-name: org.postgresql.Driver  # Correct PostgreSQL driver
    url: jdbc:postgresql://localhost:5432/carservicedb?createDatabaseIfNotExist=true  # Correct PostgreSQL URL (remove createDatabaseIfNotExist)
    username: "postgres"   # Replace with your PostgreSQL username
    password: ""
  jpa:
    hibernate:
      ddl-auto: update  # See note below about 'update'
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect # Specify the correct dialect
    properties:
      hibernate:
        format_sql: true # Optional: Formats SQL for better readability in logs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always