server:
  port: 8081

spring:
  application:
    name: service-client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
  datasource:
    driver-class-name: org.postgresql.Driver  # Correct PostgreSQL driver
    url: jdbc:postgresql://localhost:5432/clientservicedb?createDatabaseIfNotExist=true
    username: "postgres"
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
